apiVersion: apps/v1
kind: Deployment
metadata:
   name: cicdproj
spec:
  selector:
    matchLabels:
      app: cicdproj
  template:
    metadata:
      labels:
        app: cicdproj
    spec:
      containers:
      - name: cicdproj
        image: dockerimage/cicdproj
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
  
metadata:
  name: cicdproj
spec:
  type: LoadBalancer
  selector:
    app: cicdproj
  ports:
  - port: 5000
    targetPort: 5000
