apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdproj
  labels:
    app: cicdproj
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cicdproj
      
  template:
    metadata:
      labels:
        app: cicdproj
        tier: cicdproj
    spec:
      containers:
        - name: cicdproj
          image: dockerimage/cicdproj
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: cicdproj


---
apiVersion: v1
kind: Service
metadata:
  name: cicdproj
  labels:
    app: cicdproj
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: cicdproj
    tier: cicdproj
  type: LoadBalancer