apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cicdproj
  name: cicdproj
spec:
  selector:
    matchLabels:
      app: cicdproj
  template:
    metadata:
      labels:
        app: cicdproj
    spec:
      containers:
      - name: cicdproj
        image: dockerimage/cicdproj
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
  
metadata:
  namespace: cicdproj
  name: cicdproj
spec:
  type: LoadBalancer
  selector:
    app: cicdproj
  ports:
  - port: 8081
    targetPort: 8080
